
trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

# variables:
#   solution: '**/*.sln'
#   buildPlatform: 'Any CPU'
#   buildConfiguration: 'Release'


stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build_Server
    displayName: Prepare build environment
    steps:
      - script: |
            sudo apt update 
            sudo apt install nodejs npm 
            sudo npm install i -g @ionic/cli 
            ls -l 
    
  # - job: Build_webapp  
  #   displayName: Build webapp  
  #   steps:
  #       - script: |
  #             ionic build --prod 
    
              
        
         







